### ISSUE TITLE
Improving login experience

### ISSUE THREAD

**Issue by kvetak** [netx-as/docs#2]
After the successful login through console, I would expect to see as message of the day:

```
  _   _      _    __  __
 | \ | | ___| |_  \ \/ /
 |  \| |/ _ \ __|  \  / 
 | |\  |  __/ |_   /  \ 
 |_| \_|\___|\__| /_/\_\
```
                      
This would emphase that I am already in netc console. With the current approach, I was typing bash commands after initial login.

**Comment by mgregr** [comment]
Already implemented
